#include "clangdb.h"
#include <iostream>
#include <llvm/Support/Casting.h>

namespace clang {
namespace database _CLANGDB_VISIBILITY {

std::string TypeofLocalCXXMethodDecl(CXXMethodDecl *Method,
                                     AccessSpecifier Access) {
  std::string MangledRetTy = MangleType(Method->getReturnType().getTypePtr());
  std::string Ret = Method->isStatic() ? "6static" : "";
  Ret += (Method->isConst() ? "5const" : "");
  Ret += EncodeAccessSpecifier(Access);
  Ret += EncodeNs(MangledRetTy);
  return Ret;
}

struct ClassDeclVisitor {
private:
  BuildVisitorContext &Context;
  std::string WholeName;

  void IterateMembers(CXXRecordDecl *RD, int Depth);

  static void AppendParmList(std::string &ShortName,
                             const FunctionProtoType *Proto) {
    for (auto Iter = Proto->param_type_begin(); Iter != Proto->param_type_end();
         Iter++) {
      const Type *ParamType = Iter->getTypePtr();
      ShortName += MangleType(ParamType);
    }
    if (Proto->getNumParams() == 0) {
      ShortName += "v"; /* void */
    }
  }

public:
  ClassDeclVisitor(BuildVisitorContext &Ctx)
      : Context(Ctx), WholeName(Ctx.CurrentNamespace()) {}

  void TraverseCXXRecordDecl(CXXRecordDecl *RD, int depth = 0,
                             AccessSpecifier Access = AccessSpecifier::AS_none);
  void
  TraverseClassTemplateDecl(ClassTemplateDecl *CTD, int Depth = 0,
                            AccessSpecifier Access = AccessSpecifier::AS_none);
};

void ClassDeclVisitor::IterateMembers(CXXRecordDecl *RD, int Depth) {
  AccessSpecifier CurrentAccess =
      RD->isStruct() ? AccessSpecifier::AS_public
                     : AccessSpecifier::AS_private /* isClass() */;

  auto iter = RD->decls_begin();
  auto end = RD->decls_end();
  if (iter == end) {
    return;
  }

  /**
   * ++iter is to skip the extra CXXRecordDecl generated by clang.
   * For example,
   * <blockquote><pre>
   * struct Foo {
   *
   * </pre></blockquote>
   *
   * in the AST becomes:
   *
   * <blockquote><pre>
   * CXXRecordDecl(Foo) {
   *     CXXRecordDecl(Foo)  // extra decl
   * }</pre></blockquote>
   */
  for (++iter; iter != end; iter++) {
    auto *Member = *iter;
    if (auto *LocalClass = llvm::dyn_cast<CXXRecordDecl>(Member)) {
      const auto CurNsWholename = Context.CurrentNamespace();
      const auto ShortName = EncodeNs(LocalClass->getName());
      const auto FullName = CurNsWholename + ShortName;

      this->TraverseCXXRecordDecl(LocalClass, Depth + 1, CurrentAccess);
    } else if (auto *Method = llvm::dyn_cast<CXXMethodDecl>(Member)) {
      std::string ShortName = EncodeNs(Method->getName());
      const Type *MethodType = Method->getType().getTypePtr();
      assert(dyn_cast<const FunctionType>(MethodType) != nullptr);
      if (auto *Proto = dyn_cast<const FunctionProtoType>(MethodType)) {
        assert(Proto != nullptr);
        AppendParmList(ShortName, Proto);
        Context.GetDatabase().InsertIntoClass(
            WholeName, ShortName,
            TypeofLocalCXXMethodDecl(Method, CurrentAccess));
      }
    } else if (auto *FTD = dyn_cast<FunctionTemplateDecl>(Member)) {
      std::string ShortName = MangleFunctionTemplate(*FTD);
      auto *Fn = FTD->getTemplatedDecl();
      AppendParmList(ShortName, dyn_cast<const FunctionProtoType>(
                                    Fn->getType().getTypePtr()));
      Context.GetDatabase().InsertIntoClass(
          WholeName, ShortName,
          TypeofLocalCXXMethodDecl(dyn_cast<CXXMethodDecl>(Fn), CurrentAccess));
    } else if (auto *Field = llvm::dyn_cast<FieldDecl>(Member)) {
      /**
       * TODO: insert into the class table.
       */
      llvm::errs() << Field->getName() << "\n";
    } else if (auto *Access = llvm::dyn_cast<AccessSpecDecl>(Member)) {
      CurrentAccess = Access->getAccess();
    } else if (auto *CTD = llvm::dyn_cast<ClassTemplateDecl>(Member)) {
      this->TraverseClassTemplateDecl(CTD, Depth + 1, CurrentAccess);
    }
  }
}

void ClassDeclVisitor::TraverseCXXRecordDecl(CXXRecordDecl *RD, int Depth,
                                             AccessSpecifier Access) {
  if (unlikely(Depth >= MAX_RECURSION_DEPTH)) {
    llvm::errs() << "Max recursion depth reached, skipping traversal of "
                 << RD->getName() << "\n";
    return;
  }

  /* Mock pushing current class. */
  std::string ShortName = EncodeNs(RD->getName());
  size_t PrevNameLen = WholeName.size();
  {
    DatabaseInterface &DB = Context.GetDatabase();
    if (Depth == 0 &&
        dyn_cast<CXXRecordDecl>(Context.NamespaceStack.back()) == nullptr) {
      /**
       * `RD` is in a namespace.
       */
      DB.InsertIntoNamespace(WholeName, ShortName, TypeofCXXRecordDecl(RD));
    } else {
      DB.InsertIntoClass(WholeName, ShortName,
                         TypeofLocalCXXRecordDecl(RD, Access));
    }
  }
  WholeName += ShortName;

  IterateMembers(RD, Depth);

  /* Mock poping current class. */
  WholeName.resize(PrevNameLen);
}

void ClassDeclVisitor::TraverseClassTemplateDecl(ClassTemplateDecl *CTD,
                                                 int Depth,
                                                 AccessSpecifier Access) {
  if (unlikely(Depth >= MAX_RECURSION_DEPTH)) {
    llvm::errs() << "Max recursion depth reached, skipping traversal of "
                 << CTD->getName() << "\n";
    return;
  }

  CXXRecordDecl *RD = CTD->getTemplatedDecl();
  std::string ShortName = MangleClassTemplate(*CTD);
  size_t PrevNameLen = WholeName.size();
  {
    DatabaseInterface &DB = Context.GetDatabase();
    if (Depth == 0 &&
        dyn_cast<CXXRecordDecl>(Context.NamespaceStack.back()) == nullptr) {
      DB.InsertIntoNamespace(WholeName, ShortName, TypeofCXXRecordDecl(RD));
    } else {
      DB.InsertIntoClass(WholeName, ShortName,
                         TypeofLocalCXXRecordDecl(RD, Access));
    }
  }
  WholeName += ShortName;

  IterateMembers(RD, Depth);

  /* Mock poping current class. */
  WholeName.resize(PrevNameLen);
}

std::string BuildVisitorContext::CurrentNamespace() const {
  std::string ret = "";
  size_t Depth = NamespaceStack.size();

  for (size_t i = 1 /* skip translation unit */; i < Depth; i++) {
    auto *Ptr = NamespaceStack[i];
    if (auto *ND = dyn_cast<NamespaceDecl>(Ptr)) {
      ret += EncodeNs(ND->getName());
    } else if (auto *RD = dyn_cast<CXXRecordDecl>(Ptr)) {
      ret += EncodeNs(RD->getName());
    } else {
      llvm::errs() << "Unexpected decl context in namespace stack: "
                   << Ptr->getDeclKindName() << "\n";
      assert(0);
    }
  }

  return ret;
}

bool BuildVisitor::TraverseNamespaceDecl(NamespaceDecl *ND) {
  DeclContext *CurNamespace = Context.CurrentDeclContext();
  /**
   * By default, the `RecursiveASTVisitor` traverse in preorder.
   * This means `ND` is lateral to `CurNamespace`, and we need to
   * pop the stack until we find the common ancestor of `ND` and
   * `CurNamespace`, then push `ND` into the stack.
   */
  Context.PopUntilFindParent(ND->getParent());
  Context.EnterNamespace(ND);

  return RecursiveASTVisitor<BuildVisitor>::TraverseNamespaceDecl(ND);
}

bool BuildVisitor::TraverseCXXRecordDecl(CXXRecordDecl *RD) {
  bool isClassOrStruct = RD->isClass() || RD->isStruct();
  if (!isClassOrStruct) {
    return RecursiveASTVisitor<BuildVisitor>::TraverseCXXRecordDecl(RD);
  }

  Context.PopUntilFindParent(RD->getDeclContext());

  /* we do traversal on our own, with RD->decls(). */
  ClassDeclVisitor Visitor(this->Context);
  Visitor.TraverseCXXRecordDecl(RD);
  return true;
}

bool BuildVisitor::TraverseClassTemplateDecl(ClassTemplateDecl *CTD) {
  ClassDeclVisitor Visitor(this->Context);
  Visitor.TraverseClassTemplateDecl(CTD);
  return true;
}

} /* namespace database _CLANGDB_VISIBILITY */
} /* namespace clang */
