#include "clangdb.h"
#include <iostream>
#include <llvm/Support/Casting.h>

namespace clang {
namespace database _CLANGDB_VISIBILITY {

void EncodeBaseClasses(std::string &Dest, const CXXRecordDecl *RD) {
  RD = RD->getDefinition();
  if (RD == nullptr) {
    return;
  }

  const auto &Bases = RD->bases();
  if (Bases.empty()) {
    return;
  }
  Dest += "7virtual";
  for (auto Iter = Bases.begin(); Iter != Bases.end(); Iter++) {
    const CXXRecordDecl *Base = Iter->getType()->getAsCXXRecordDecl();
    if (!Base) {
      continue;
    }
    Dest += EncodeAccessSpecifier(Iter->getAccessSpecifier());
    Dest += (Iter->isVirtual() ? "7virtual" : "");
    Dest += MangleRecordDecl(Base);
  }
}

std::string TypeofLocalCXXMethodDecl(CXXMethodDecl *Method,
                                     AccessSpecifier Access) {
  std::string MangledRetTy = MangleType(Method->getReturnType().getTypePtr());
  std::string Ret = Method->isStatic() ? "6static" : "";
  Ret += (Method->isConst() ? "5const" : "");
  Ret += (Method->isPureVirtual() ? "7virtual" : "");
  Ret += EncodeAccessSpecifier(Access);
  Ret += EncodeNs(MangledRetTy);
  return Ret;
}

std::string TypeofClassMember(FieldDecl *Value, AccessSpecifier Access) {
  /**
   * return format: mangled "(static::)(const::)(mutable::)mangled(type)"
   */
  std::string MangledTy = MangleType(Value->getType().getTypePtr());
  std::string Ret = Value->isMutable() ? "7mutable" : "";
  Ret += EncodeAccessSpecifier(Access);
  Ret += EncodeNs(MangledTy);
  return Ret;
}

std::string TypeofVarDecl(VarDecl *Value, AccessSpecifier Access) {
  std::string MangledTy = MangleType(Value->getType().getTypePtr());
  std::string Ret = Value->isStaticDataMember() ? "6static" : "";
  Ret +=
      (Access == AccessSpecifier::AS_none) ? "" : EncodeAccessSpecifier(Access);
  Ret += (Value->isConstexpr()) ? "9constexpr" : "";
  Ret += EncodeNs(MangledTy);
  return Ret;
}

static void AppendParmList(std::string &ShortName,
                           const FunctionProtoType *Proto) {
  MangleFunctionParmList(ShortName, Proto);
}

/**
 * Traversing and collecting VarDecl inside Translation Unit
 * or Namepsaces.
 */
struct ScopedDeclVisitor {
  BuildVisitorContext &Context;
  std::string WholeName;

  ScopedDeclVisitor(BuildVisitorContext &Ctx, std::string WholeName)
      : Context(Ctx), WholeName(std::move(WholeName)) {}

  void IterateMembers(DeclContext *DC);
};

void ScopedDeclVisitor::IterateMembers(DeclContext *DC) {
  for (auto *D : DC->decls()) {
    if (auto *VD = llvm::dyn_cast<VarDecl>(D)) {
      std::string ShortName = EncodeNs(VD->getName());
      Context.GetDatabase().InsertIntoNamespace(
          WholeName, ShortName, TypeofVarDecl(VD, AccessSpecifier::AS_none));
    }
  }
}

struct ClassDeclVisitor {
private:
  BuildVisitorContext &Context;
  std::string WholeName;

  void IterateMembers(CXXRecordDecl *RD, int Depth);

public:
  ClassDeclVisitor(BuildVisitorContext &Ctx)
      : Context(Ctx), WholeName(Ctx.CurrentNamespace()) {}

  void TraverseCXXRecordDecl(CXXRecordDecl *RD, int depth = 0,
                             AccessSpecifier Access = AccessSpecifier::AS_none);
  void
  TraverseClassTemplateDecl(ClassTemplateDecl *CTD, int Depth = 0,
                            AccessSpecifier Access = AccessSpecifier::AS_none);
};

void ClassDeclVisitor::IterateMembers(CXXRecordDecl *RD, int Depth) {
  AccessSpecifier CurrentAccess =
      RD->isClass() ? AccessSpecifier::AS_private
                    : AccessSpecifier::AS_public /* struct/union */;

  auto iter = RD->decls_begin();
  auto end = RD->decls_end();
  if (iter == end) {
    return;
  }

  /**
   * ++iter is to skip the extra CXXRecordDecl generated by clang.
   * For example,
   * <blockquote><pre>
   * struct Foo {
   *
   * </pre></blockquote>
   *
   * in the AST becomes:
   *
   * <blockquote><pre>
   * CXXRecordDecl(Foo) {
   *     CXXRecordDecl(Foo)  // extra decl
   * }</pre></blockquote>
   */
  for (++iter; iter != end; iter++) {
    auto *Member = *iter;
    if (auto *LocalClass = llvm::dyn_cast<CXXRecordDecl>(Member)) {
      const auto CurNsWholename = Context.CurrentNamespace();
      const auto ShortName = EncodeNs(LocalClass->getName());
      const auto FullName = CurNsWholename + ShortName;

      if (LocalClass->getDeclContext() == RD)
        ;
      else {
        RD->dump(llvm::errs());
        assert(0);
      }
      this->TraverseCXXRecordDecl(LocalClass, Depth + 1, CurrentAccess);
    } else if (auto *Method = llvm::dyn_cast<CXXMethodDecl>(Member)) {
      std::string ShortName = EncodeFunctionName(Method);
      const Type *MethodType = Method->getType().getTypePtr();
      assert(dyn_cast<const FunctionType>(MethodType) != nullptr);
      if (auto *Proto = dyn_cast<const FunctionProtoType>(MethodType)) {
        assert(Proto != nullptr);
        AppendParmList(ShortName, Proto);
        Context.GetDatabase().InsertIntoClass(
            WholeName, ShortName,
            TypeofLocalCXXMethodDecl(Method, CurrentAccess));
      }
    } else if (auto *FTD = dyn_cast<FunctionTemplateDecl>(Member)) {
      std::string ShortName = MangleFunctionTemplate(*FTD);
      auto *Fn = FTD->getTemplatedDecl();
      AppendParmList(ShortName, dyn_cast<const FunctionProtoType>(
                                    Fn->getType().getTypePtr()));
      Context.GetDatabase().InsertIntoClass(
          WholeName, ShortName,
          TypeofLocalCXXMethodDecl(dyn_cast<CXXMethodDecl>(Fn), CurrentAccess));
    } else if (auto *Field = llvm::dyn_cast<FieldDecl>(Member)) {
      std::string ShortName = EncodeNs(Field->getName());
      Context.GetDatabase().InsertIntoClass(
          WholeName, ShortName, TypeofClassMember(Field, CurrentAccess));
    } else if (auto *Access = llvm::dyn_cast<AccessSpecDecl>(Member)) {
      CurrentAccess = Access->getAccess();
    } else if (auto *CTD = llvm::dyn_cast<ClassTemplateDecl>(Member)) {
      this->TraverseClassTemplateDecl(CTD, Depth + 1, CurrentAccess);
    } else if (auto *VD = llvm::dyn_cast<VarDecl>(Member)) {
      std::string ShortName = EncodeNs(VD->getName());
      Context.GetDatabase().InsertIntoClass(WholeName, ShortName,
                                            TypeofVarDecl(VD, CurrentAccess));
    }
  }
}

void ClassDeclVisitor::TraverseCXXRecordDecl(CXXRecordDecl *RD, int Depth,
                                             AccessSpecifier Access) {
  if (unlikely(Depth >= MAX_RECURSION_DEPTH)) {
    llvm::errs() << "Max recursion depth reached, skipping traversal of "
                 << RD->getName() << "\n";
    return;
  }

  /* Mock pushing current class. */
  std::string ShortName = EncodeNs(RD->getName());
  size_t PrevNameLen = WholeName.size();
  {
    DatabaseInterface &DB = Context.GetDatabase();
    if (Depth == 0 && !Context.TopIsCXXRecordDecl()) {
      /**
       * `RD` is in a namespace.
       */
      DB.InsertIntoNamespace(WholeName, ShortName, TypeofCXXRecordDecl(RD));
    } else {
      DB.InsertIntoClass(WholeName, ShortName,
                         TypeofLocalCXXRecordDecl(RD, Access));
    }
  }
  WholeName += ShortName;

  IterateMembers(RD, Depth);

  /* Mock poping current class. */
  WholeName.resize(PrevNameLen);
}

void ClassDeclVisitor::TraverseClassTemplateDecl(ClassTemplateDecl *CTD,
                                                 int Depth,
                                                 AccessSpecifier Access) {
  if (unlikely(Depth >= MAX_RECURSION_DEPTH)) {
    llvm::errs() << "Max recursion depth reached, skipping traversal of "
                 << CTD->getName() << "\n";
    return;
  }

  CXXRecordDecl *RD = CTD->getTemplatedDecl();
  std::string ShortName = MangleClassTemplate(*CTD);
  size_t PrevNameLen = WholeName.size();
  {
    DatabaseInterface &DB = Context.GetDatabase();
    if (Depth == 0 && !Context.TopIsCXXRecordDecl()) {
      DB.InsertIntoNamespace(WholeName, ShortName, TypeofCXXRecordDecl(RD));
    } else {
      DB.InsertIntoClass(WholeName, ShortName,
                         TypeofLocalCXXRecordDecl(RD, Access));
    }
  }
  WholeName += ShortName;

  IterateMembers(RD, Depth);

  /* Mock poping current class. */
  WholeName.resize(PrevNameLen);
}

std::string BuildVisitorContext::CurrentNamespace() const {
  return MangleNamespaceStack(NamespaceStack, 1
                              /* Skip translation unit decl. */);
}

bool BuildVisitor::TraverseNamespaceDecl(NamespaceDecl *ND) {
  DeclContext *CurNamespace = Context.CurrentDeclContext();
  /**
   * By default, the `RecursiveASTVisitor` traverse in preorder.
   * This means `ND` is lateral to `CurNamespace`, and we need to
   * pop the stack until we find the common ancestor of `ND` and
   * `CurNamespace`, then push `ND` into the stack.
   */
  Context.PopUntilFindParent(ND->getParent());
  Context.EnterNamespace(ND);

  ScopedDeclVisitor Visitor{Context, Context.CurrentNamespace()};
  Visitor.IterateMembers(ND);

  return RecursiveASTVisitor<BuildVisitor>::TraverseNamespaceDecl(ND);
}

bool BuildVisitor::TraverseCXXRecordDecl(CXXRecordDecl *RD) {
  Context.PopUntilFindParent(RD->getDeclContext());

  /* we do traversal on our own, with RD->decls(). */
  ClassDeclVisitor Visitor(this->Context);
  Visitor.TraverseCXXRecordDecl(RD);
  return true;
}

bool BuildVisitor::TraverseClassTemplateDecl(ClassTemplateDecl *CTD) {
  ClassDeclVisitor Visitor(this->Context);
  Visitor.TraverseClassTemplateDecl(CTD);
  return true;
}

bool BuildVisitor::TraverseFunctionDecl(FunctionDecl *FD) {
  Context.PopUntilFindParent(FD->getDeclContext());
  std::string ShortName = EncodeFunctionName(FD);
  const auto *Proto =
      dyn_cast<const FunctionProtoType>(FD->getType().getTypePtr());
  assert(Proto != nullptr);
  AppendParmList(ShortName, Proto);
  auto *RetType = FD->getReturnType().getTypePtr();

  Context.GetDatabase().InsertIntoNamespace(Context.CurrentNamespace(),
                                            ShortName, MangleType(RetType));

  /**
   * Do not traverse into the function body, since we only care about the
   * declaration of the function.
   */
  return true;
}

bool BuildVisitor::TraverseFunctionTemplateDecl(FunctionTemplateDecl *FTD) {
  Context.PopUntilFindParent(FTD->getDeclContext());
  std::string ShortName = MangleFunctionTemplate(*FTD);
  auto *Fn = FTD->getTemplatedDecl();
  AppendParmList(ShortName,
                 dyn_cast<const FunctionProtoType>(Fn->getType().getTypePtr()));
  auto *RetType = Fn->getReturnType().getTypePtr();

  Context.GetDatabase().InsertIntoNamespace(Context.CurrentNamespace(),
                                            ShortName, MangleType(RetType));

  /**
   * Do not traverse into the function body, since we only care about the
   * declaration of the function template.
   */
  return true;
}

bool BuildVisitor::TraverseTranslationUnitDecl(TranslationUnitDecl *TU) {
  Context.EnterTranslationUnit(TU);

  ScopedDeclVisitor Visitor{Context, Context.CurrentNamespace()};
  Visitor.IterateMembers(TU);
  return RecursiveASTVisitor<BuildVisitor>::TraverseTranslationUnitDecl(TU);
}

bool BuildVisitor::TraverseLinkageSpecDecl(LinkageSpecDecl *LSD) {
  Context.PopUntilFindParent(LSD->getParent());
  Context.EnterLinkageSpecDecl(LSD);

  ScopedDeclVisitor Visitor{Context, Context.CurrentNamespace()};
  Visitor.IterateMembers(LSD);
  return RecursiveASTVisitor<BuildVisitor>::TraverseLinkageSpecDecl(LSD);
}

} /* namespace database _CLANGDB_VISIBILITY */
} /* namespace clang */
