#include "clangdb.h"
#include <iostream>

namespace clang {
namespace database _CLANGDB_VISIBILITY {

struct ClassDeclVisitor {
private:
  BuildVisitorContext &Context;

public:
  ClassDeclVisitor(BuildVisitorContext &Ctx) : Context(Ctx) {}

  void TraverseCXXRecordDecl(CXXRecordDecl *RD, int depth = 0);
};

void ClassDeclVisitor::TraverseCXXRecordDecl(CXXRecordDecl *RD, int depth) {
  if (unlikely(depth >= MAX_RECURSION_DEPTH)) {
    llvm::errs() << "Max recursion depth reached, skipping traversal of "
                 << RD->getName() << "\n";
    return;
  }
  AccessSpecifier CurrentAccess =
      RD->isStruct() ? AccessSpecifier::AS_public
                     : AccessSpecifier::AS_private /* isClass() */;

  auto iter = RD->decls_begin();
  auto end = RD->decls_end();
  /**
   * ++iter is to skip the extra CXXRecordDecl generated by clang.
   * For example,
   * <blockquote><pre>
   * struct Foo {
   *
   * </pre></blockquote>
   *
   * in the AST becomes:
   *
   * <blockquote><pre>
   * CXXRecordDecl(Foo) {
   *     CXXRecordDecl(Foo)  // extra decl
   * }</pre></blockquote>
   */
  for (++iter; iter != end; iter++) {
    auto *Member = *iter;
    if (auto *LocalClass = llvm::dyn_cast<CXXRecordDecl>(Member)) {
      const auto CurNsWholename = Context.CurrentNamespace();
      const auto ShortName = EncodeNs(LocalClass->getName());
      const auto FullName = CurNsWholename + ShortName;

      Context.EnterClass(LocalClass);
      this->TraverseCXXRecordDecl(LocalClass, depth + 1);
      Context.LeaveNamespaceOrClass();
    } else if (auto *Method = llvm::dyn_cast<CXXMethodDecl>(Member)) {
      /**
       * TODO: insert into the class table.
       */
      llvm::errs() << Method->getName() << "\n";
    } else if (auto *Field = llvm::dyn_cast<FieldDecl>(Member)) {
      /**
       * TODO: insert into the class table.
       */
      llvm::errs() << Field->getName() << "\n";
    } else if (auto *Access = llvm::dyn_cast<AccessSpecDecl>(Member)) {
      CurrentAccess = Access->getAccess();
    }
  }
}

std::string BuildVisitorContext::CurrentNamespace() const {
  std::string ret = "";
  size_t Depth = NamespaceStack.size();

  for (size_t i = 1 /* skip translation unit */; i < Depth; i++) {
    auto *Ptr = NamespaceStack[i];
    if (auto *ND = dyn_cast<NamespaceDecl>(Ptr)) {
      ret += EncodeNs(ND->getName());
    } else if (auto *RD = dyn_cast<CXXRecordDecl>(Ptr)) {
      ret += EncodeNs(RD->getName());
    } else {
      llvm::errs() << "Unexpected decl context in namespace stack: "
                   << Ptr->getDeclKindName() << "\n";
      assert(0);
    }
  }

  return ret;
}

bool BuildVisitor::TraverseNamespaceDecl(NamespaceDecl *ND) {
  DeclContext *CurNamespace = Context.CurrentDeclContext();
  /**
   * By default, the `RecursiveASTVisitor` traverse in preorder.
   * This means `ND` is lateral to `CurNamespace`, and we need to
   * pop the stack until we find the common ancestor of `ND` and
   * `CurNamespace`, then push `ND` into the stack.
   */
  Context.PopUntilFindParent(ND->getParent());
  Context.EnterNamespace(ND);

  return RecursiveASTVisitor<BuildVisitor>::TraverseNamespaceDecl(ND);
}

bool BuildVisitor::TraverseCXXRecordDecl(CXXRecordDecl *RD) {
  bool isClassOrStruct = RD->isClass() || RD->isStruct();
  if (isClassOrStruct) {
    Context.PopUntilFindParent(RD->getDeclContext());
    Context.EnterClass(RD);
  } else {
    return RecursiveASTVisitor<BuildVisitor>::TraverseCXXRecordDecl(RD);
  }

  /* we do traversal on our own, with RD->decls(). */
  ClassDeclVisitor Visitor(this->Context);
  Visitor.TraverseCXXRecordDecl(RD);
  Context.LeaveNamespaceOrClass();
  return true;
}

} /* namespace database _CLANGDB_VISIBILITY */
} /* namespace clang */
